name: goatdownloder
description: "Advanced Flutter Video Downloader - Professional video downloading app with multi-platform support"
publish_to: 'eclipse dev'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  
  # Networking & HTTP
  dio: ^5.4.0
  connectivity_plus: ^5.0.2
  
  # Video Processing & Player
  video_player: ^2.8.1
  chewie: ^1.7.5
  
  # File System & Storage
  path_provider: ^2.1.2
  permission_handler: ^11.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # UI & Animations
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  dynamic_color: ^1.7.0
  
  # Localization & Accessibility
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  
  # Utilities
  share_plus: ^7.2.2
  url_launcher: ^6.2.2
  package_info_plus: ^5.0.1
  device_info_plus: ^9.1.1
  crypto: ^3.0.3
  get_it: ^8.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.7
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/animations/
    - assets/icons/
  
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
