name: goatdownloader
description: "Advanced Flutter Video Downloader - Professional video downloading app with multi-platform support"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  
  # Networking & HTTP
  dio: ^5.7.0
  connectivity_plus: ^6.0.5
  html: ^0.15.4
  
  # Video Processing & Player
  video_player: ^2.9.1
  chewie: ^1.8.5
  
  # File System & Storage
  path_provider: ^2.1.4
  path: ^1.9.0
  permission_handler: ^11.3.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  sqflite: ^2.3.3+1
  
  # UI & Animations
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  dynamic_color: ^1.7.0
  material_color_utilities: ^0.11.1
  
  # Localization & Accessibility
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  
  # Utilities
  share_plus: ^10.0.2
  url_launcher: ^6.3.0
  package_info_plus: ^8.0.2
  device_info_plus: ^10.1.2
  crypto: ^3.0.5
  get_it: ^8.0.0
  network_info_plus: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/animations/
    - assets/icons/
  
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700